### ISSUE TITLE
w_unmet_fp: Ghana2011

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/UHC-Time-Trend#32]
Not sure why MICS4 Ghana2011 is off, the code and data reference seems right:

See the code for your reference: 
https://github.com/Data-Whale-DC/WB-HEFPI-MICS4/blob/main/MICS4_do_w_reproductive.do

**Comment by robin-wang** [comment]
The MICS4 Ghana2011 report also has consistent value for unmet need, 26% (vs our calculated value at 24%)
MICS6 2017, we are spot on at 34%
DHS 2003 and DHS 2008 also checked reported values, we are spot-on. Propose to drop MICS4 Ghana 2011 data point if that creates a kink in the distribution. This issue is resolved.

<img width="194" alt="Screenshot 2022-04-26 at 11 52 05 AM" src="https://user-images.githubusercontent.com/32467176/165217466-044c96f6-f3c8-46a6-babf-20eb65d3c2f6.png">
